### ISSUE TITLE
missing all SCONJ

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-GSD#20]
hi, apparently the Google annotation has no SCONJ, so UD_Portuguese-GSD has no SCONJ either. 

@dan-zeman you corrected the lack of SCONJ for PUD-PT, can you get this one sorted out too, please?

**Comment by arademaker** [comment]
I [suspect](https://github.com/UniversalDependencies/UD_Portuguese-PUD/commit/7c7d4ab15dfd66f02132830c7cc77793cb3d04ba) that @dan-zeman used the `IN` xpostag as clue for making the automatic transformation. Here we don't have them. 

BTW, @dan-zeman I am now using the workbench branch for working in this corpus. But my priority is still to fix all validation errors in Bosque.

**Comment by martinpopel** [comment]
I am not sure if it is relevant here, but when converting PUD treebanks from Google style to UD, I used the following code
https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/google2ud.py#L418-L419
```python
if node.upos == 'CONJ' and node.deprel == 'mark':
    node.upos = 'SCONJ'
```
Maybe it should be rather:
```python
if node.upos in ('CONJ', 'ADP') and node.deprel == 'mark':
    node.upos = 'SCONJ'
```

BTW: you should consider applying also https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/pt/addmwt.py (`udapy -s ud.pt.AddMwt < in.conllu > out.conllu`),
so that e.g.
```
2       disso   _       X       ADPPRON
```
is changed to
```
2-3     disso   _       _       _ 
2       de      de      ADP     ADPPRON
3       isso    este    DET     _
```

**Comment by arademaker** [comment]
@martinpopel , thank you. I was working in the second first. Given that many cases contractions need to be splinted. I will try tomorrow to play with your udapi-python..

**Comment by arademaker** [comment]
Hi @martinpopel , I am getting the error

```
% udapy -s ud.pt.addMwt < pt_gsd-ud-train-0503.conllu > pt_gsd-ud-train-0503.new
2021-04-16 11:45:10,826 [WARNING] _import_blocks - Error when trying import the block ud.pt.addMwt
Traceback (most recent call last):
  File "/Users/ar/work/udapi-python/bin/udapy", line 114, in <module>
    runner.execute()
  File "/Users/ar/work/udapi-python/udapi/core/run.py", line 133, in execute
    blocks = _import_blocks(block_names, block_args)
  File "/Users/ar/work/udapi-python/udapi/core/run.py", line 94, in _import_blocks
    exec(command)  # pylint: disable=exec-used
  File "<string>", line 1, in <module>
ImportError: cannot import name 'addMwt' from 'udapi.block.ud.pt.addmwt' (/Users/ar/work/udapi-python/udapi/block/ud/pt/addmwt.py)
```

I installed udapi following using the instructions for developers.

**Comment by martinpopel** [comment]
It should be `udapy -s ud.pt.AddMwt`, i.e. with capitalized A, reflecting the name of the class (in Udapi, the filename is always lowercased class name, so the filename is deduced automatically).
